version: "3.5"

services:
  db:
    container_name: trpc-db
    image: postgres:14.6-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=trpc
    volumes:
      - trpc-db:/var/lib/postgres/data

volumes:
  trpc-db: